# Generated by Django 2.1.2 on 2018-10-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('phone', models.CharField(max_length=20)),
                ('private_key', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
